name: Helloworld #workflowname 
on: push
jobs:
  Printing_HelloWorld_Program: #job name
    runs-on: windows-latest
    steps: #stage
       #action1
      - name: printing hello world 
        run: echo "hello world" 
        #action2
      - name: printing hello india 
        run: echo "hello india" 
  Printing_sumofNumbers:
    runs-on: ubuntu-latest
    steps:
      - name: sum of numbers 
        run: |
          var1=10
          var2=20
          sum=$(($var1 + $var2))
          echo $sum
  Printing_software_versions:
    runs-on: windows-latest
    steps:
      - name: identifying the versions 
        run: |
          node --version
          npm --version
          java --version
          dotnet --version
          python --version
          nginx --version
          
            
      