name: Helloworld #workflowname 
on: push
jobs:
  Printing_HelloWorld_Program: #job name
    runs-on: windows-latest
    steps: #stage
       #action1
      - name: printing hello world 
        run: echo "hello world" 
        #action2
      - name: printing hello india 
        run: echo "hello india" 
  Printing_sumofNumbers:
    runs-on: ubuntu-latest
    steps:
      - name: sum of numbers 
        run: |
          var1=10
          var2=20
          sum=$(($var1 + $var2))
          echo $sum
  Printing_software_versions_windows:
    runs-on: windows-latest
    steps:
      - name: identifying the versions_ 
        run: |
          echo "printing node version"
          node --version
          echo "printing npm version"
          npm --version
          echo "printing java version"
          java --version
          echo "printing dotnet version"
          dotnet --version
          echo "printing python version"
          python --version
  Printing_software_versions_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: identifying the versions_ 
        run: |
          echo "printing node version"
          node --version
          echo "printing npm version"
          npm --version
          echo "printing java version"
          java --version
          echo "printing dotnet version"
          dotnet --version
          echo "printing python version"
          python --version
          echo "printing nginx version"
          nginx -V 
  Run_Shell_Commands:
    runs-on: ubuntu-latest
    steps:
      - name: identifying the processors using python command
        run: |
          import platform
          print(platform.processors())
        shell: python
  Run_Windows_Commands:
    runs-on: windows-latest
    steps:
      - name: finding the locatiosn using powershell and bash Run_Shell_Commands
        run: |
          echo "get location using powershell"
          get_location
          echo "get location using pwd"
          pwd
          
 
      

     
          
          
            
      